//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qustion
    {
        public int QustionID { get; set; }
        public int Categoryid { get; set; }
        public string QustionName { get; set; }
        public bool IsActive { get; set; }
        public bool IsMultiple { get; set; }
    }
}
